database:
  host: localhost
  port: 3306
  name: seubanco
  user: root
  password: ""
  charset: utf8mb4

app:
  debug: true
  timezone: America/Sao_Paulo
  
security:
  enable_ssl: false
  connection_timeout: 30
