# Database Configuration
database:
  type: mysql
  host: localhost
  port: 3306
  name: carsbase
  username: root
  password: "Igorpro2020#@"

  pool:
    minimum-idle: 5
    maximum-pool-size: 10
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# Timezone Settings
timezone:
  default: America/Sao_Paulo
  use-system-timezone: false

application:
  name: CarsBase
  version: 1.0-SNAPSHOT
  debug: false

